version: '3.8'

services:

  bot:
    restart: always
    build: .
    working_dir: /bot
    volumes:
      - .:/bot
    depends_on:
      - mongodb
    command: python run_bot.py
    networks:
      - avito-bot-network

  updates:
    restart: always
    build: .
    working_dir: /bot
    volumes:
      - .:/bot
    depends_on:
      - mongodb
    command: python updates.py
    networks:
      - avito-bot-network

  mongodb:
    restart: always
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./dockerdata/db:/data/db
    ports:
      - "27017:27017"
    command: mongod
    networks:
      - avito-bot-network

networks:
  avito-bot-network:
    driver: bridge